---
services:
  - docker

env:
  - distro: centos6
    init: /sbin/init
    run_opts: ""
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

before_install:
  # Pull container.
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

script:

  - container_id=$(mktemp)
  # Run container in detached state.
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/kota65535.pyenv:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm yum install -y epel-release'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm yum install -y ansible'

  # Debug
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible -m setup -i "localhost" -c local all'

  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/kota65535.pyenv/test/main.yml --syntax-check -vvvv'

  # Create test user.
  - 'docker exec "$(cat ${container_id})" env TERM=xterm useradd test01'
  - 'docker exec "$(cat ${container_id})" env TERM=xterm useradd test02'

  # Test role.
  - 'docker exec "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/kota65535.pyenv/test/main.yml -i /etc/ansible/roles/kota65535.pyenv/test/inventory -c local -vvvv'

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
