---
- name: Install packages
  include: packages.yml

- name: Check if the users exist
  shell: "id {{ item }}"
  with_items: "{{ pyenv_users }}"
  become: yes

# http://hakunin.com/six-ansible-practices
- name: Ensure github.com is a known host
  lineinfile:
    dest: "~/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Install pyenv for selected users
  git:
    repo: "{{ pyenv_repo }}"
    dest: "{{ pyenv_root }}"
    accept_hostkey: yes
    force: yes
  with_items: "{{ pyenv_users }}"
  become: yes
  become_user: "{{ item }}"

- name: Install pyenv-virtualenv plugin for selected users
  git:
    repo: "{{ pyenv_virtualenv_repo }}"
    dest: "{{ pyenv_root }}/plugins/pyenv-virtualenv"
    accept_hostkey: yes
    force: yes
  with_items: "{{ pyenv_users }}"
  become: yes
  become_user: "{{ item }}"

- name: Check if {{ pyenv_profile_path }} exists
  stat: path={{ pyenv_profile_path }}
  register: profile_path
  failed_when: not profile_path.stat.exists
- debug: var=profile_path

- set_fact:
    pyenv_profile_owner: "{{ pyenv_users }}"
  when: pyenv_profile_owner is not defined

- name: Add pyenv initialization lines to {{ pyenv_profile_path }}
  blockinfile:
    src: pyenv.sh.j2
    dest: "{{ pyenv_profile_path }}"
    owner: "{{ item }}"
    # group: root
    mode: 0644
    create: yes
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ pyenv_profile_owner }}"

# Become the one of the pyenv_users to use pyenv command
- name: Get the latest version for 'x' in version string
  script: get_latest_version.sh {{ pyenv_repo }} {{ item }}
  with_items: "{{ pyenv_python_versions }}"
  become: yes
  register: latest_versions
  changed_when: no
# - debug: var=latest_versions
- name: Set pyenv_python_versions_mod to replace version strings
  set_fact:
    pyenv_python_versions_mod: "{{ pyenv_python_versions_mod|default([]) + [ item.stdout_lines[0] ] }}"
  with_items: "{{ latest_versions.results }}"
# - debug: var=pyenv_python_versions_mod

- name: Install Python interpreters {{ pyenv_python_versions_mod }} for select users
  shell: ${SHELL} -lc "pyenv install {{ item[1] }}"
  args:
    creates: "{{ pyenv_root }}/versions/{{ item[1] }}/bin/python"
  with_nested:
    - "{{ pyenv_users }}"
    - "{{ pyenv_python_versions_mod }}"
  become: yes
  become_user: "{{ item[0] }}"
  when: pyenv_python_versions is defined

# Become the one of the pyenv_users to use pyenv command
- name: Get the latest version for 'x' in version string
  script: get_latest_version.sh {{ pyenv_repo }} {{ item.py_version }}
  with_items: "{{ pyenv_virtualenvs }}"
  become: yes
  register: latest_versions
# - debug: var=latest_versions
- name: Set pyenv_virtualenvs_mod to replace version strings
  set_fact:
    pyenv_virtualenvs_mod: "{{ pyenv_virtualenvs_mod|default([]) +  [ { 'py_version': item[0].stdout_lines[0], 'venv_name': item[1].venv_name } ] }}"
  with_together:
    - "{{ latest_versions.results }}"
    - "{{ pyenv_virtualenvs }}"
- debug: var=pyenv_virtualenvs_mod

- name: Create virtual environments
  shell: ${SHELL} -lc "printenv && pyenv virtualenv {{ item[1].py_version }} {{ item[1].venv_name }}"
         creates="{{ pyenv_root }}/versions/{{ item[1].venv_name }}/bin/python"
  with_nested:
    - "{{ pyenv_users }}"
    - "{{ pyenv_virtualenvs_mod|default([]) }}"
  become: yes
  become_user: "{{ item[0] }}"

