---
- name: Install development packages to compile Python versions (RedHat)
  yum:
      pkg: "{{ item }}"
      state: present
  with_items:
      - gcc
      - make
      - patch
      - sqlite-devel
      - readline-devel
      - openssl-devel
      - bzip2-devel
      - gdbm-devel
      - git
      - bzip2
      - perl-Sort-Versions
  become: yes
  when: ansible_distribution in ('CentOS', 'RedHat')
- name: Install development packages to compile Python versions (Fedora)
  dnf:
      pkg: "{{ item }}"
      state: present
  with_items:
      - gcc
      - make
      - patch
      - sqlite-devel
      - readline-devel
      - openssl-devel
      - bzip2-devel
      - gdbm-devel
      - git
      - bzip2
      - perl-Sort-Versions
  become: yes
  when: ansible_distribution == 'Fedora'
- name: Install development packages to compile Python versions (Arch)
  package: name={{item}} state=present
  with_items:
    - openssl
    - gcc
    - make
    - patch
    - sqlite
    - readline
    - bzip2
    - gdbm
    - git
    - perl-sort-versions
  when: ansible_distribution == 'Archlinux'
  become: yes
- name: Install development packages to compile Python versions (Debian)
  package: name={{item}} state=present update_cache=yes
  with_items:
    - gcc
    - make
    - patch
    - libsqlite3-dev
    - libreadline-dev
    - libbz2-dev
    - libssl-dev
    - libgdbm-dev
    - git
    - bzip2
    - libsort-versions-perl
  when: ansible_os_family == 'Debian'
  become: yes
- name: Install development packages to compile Python versions (MacOSX)
  homebrew: name={{item}} state=present update_homebrew=yes
  with_items:
    - readline
    - xz
    - perl
    - cpanminus
  when: ansible_distribution == 'MacOSX'
- name: Install development packages to compile Python versions (MacOSX)
  cpanm: name="Sort::Versions"
  become: yes
  when: ansible_distribution == 'MacOSX'
