---
- name: Install development packages to compile Python versions (RedHat)
  yum:
      pkg: "{{ item }}"
      state: present
  with_items:
      - gcc
      - make
      - patch
      - sqlite-devel
      - readline-devel
      - openssl-devel
      - bzip2-devel
      - gdbm-devel
      - git
      - bzip2
      - perl-Sort-Versions
  become: yes
  when: ansible_distribution in ('CentOS', 'RedHat')
- name: Install development packages to compile Python versions (Fedora)
  dnf:
      pkg: "{{ item }}"
      state: present
  with_items:
      - gcc
      - make
      - patch
      - sqlite-devel
      - readline-devel
      - openssl-devel
      - bzip2-devel
      - gdbm-devel
      - git
      - bzip2
      - perl-Sort-Versions
  become: yes
  when: "'Fedora' in ansible_distribution"
- name: Install development packages to compile Python versions (Arch)
  package: name={{item}} state=present
  with_items:
    - openssl
    - gcc
    - make
    - patch
    - sqlite
    - readline
    - bzip2
    - gdbm
    - git
    - perl-sort-versions
  when: "'Archlinux' in ansible_distribution"
  become: yes
- name: Install development packages to compile Python versions (Debian)
  package: name={{item}} state=present update_cache=yes
  with_items:
    - gcc
    - make
    - patch
    - libsqlite3-dev
    - libreadline-dev
    - libbz2-dev
    - libssl-dev
    - libgdbm-dev
    - git
    - bzip2
    - libsort-versions-perl
  when: "'Debian' in ansible_os_family"
  become: yes
